### ISSUE TITLE
Release the Implication Dataset

### ISSUE THREAD

**Issue by yanaiela** [marcotcr/qa_consistency#3] opened 2021-01-02 14:35 UTC
Hey,

Cool paper!
Thanks for releasing the code.

Any chance you can release the implication dataset you generate from SQuAD?
I know that you provide the code to generate it, but it would be simpler to download it directly.

**Comment by shinochin** [comment] 2021-03-25 05:55
@marcotcr 
Hi, thank you for publishing the code.

I also want to reproduce the results in your paper.
Is it possible to release the implication dataset generated from the SQuAD Training set as well as Dev set?
I tried to reproduce, but I couldn't due to some errors regarding some frameworks (e.g., allennlp).
Therefore, releasing the version of frameworks would be also helpful...

Thank you very much in advance.

**Comment by shinochin** [comment] 2021-03-25 06:09
For example, I couldn't use the old dependency parser ("https://s3-us-west-2.amazonaws.com/allennlp/models/biaffine-dependency-parser-ptb-2018.08.23.tar.gz"), so
I use instead a new one ("https://storage.googleapis.com/allennlp-public-models/biaffine-dependency-parser-ptb-2020.04.06.tar.gz").

And I replace "benepar_en_small" with "benepar_en3" to avoid some errors.

Then, I get this result. I couldn't reproduce the result...
Please kindly consider to release the implications generated from the SQuAD traininig set.

![スクリーンショット 2021-03-25 15 05 54](https://user-images.githubusercontent.com/16998772/112426891-143dfd00-8d7c-11eb-8bf6-0be9aabfa5f6.png)

**Comment by marcotcr** [comment] 2021-06-02 21:52
@yanaiela [Here](https://github.com/marcotcr/qa_consistency/raw/master/precomputed/squad_imps.zip)
@KazutoshiShinoda Fixed in 3d901dd

Sorry for the terrible delay in responding

**Closed by marcotcr** 2021-06-02 21:52 UTC
